import re
import json
from typing import Dict, Any, List, Set


class SQLValidator:
    """
    A class to validate SQL queries generated by the AI chatbot.
    It checks for safety (e.g., preventing dangerous operations)
    and adherence to a defined database schema.
    """

    def __init__(self, schema_file_path):
        self.schema_definition = self._load_schema(schema_file_path)
        self.keywords = {
            "SELECT", "FROM", "WHERE", "JOIN", "INSERT", "UPDATE", "DELETE",
            "AND", "OR", "NOT", "GROUP", "BY", "ORDER", "LIMIT", "OFFSET",
            "HAVING", "AS", "ON", "IN", "LIKE", "BETWEEN", "IS", "NULL",
            "CREATE", "ALTER", "DROP", "TRUNCATE", "UNION", "ALL", "EXISTS",
            "INNER", "LEFT", "RIGHT", "OUTER", "FULL", "CROSS", "NATURAL",
            "ASC", "DESC", "DISTINCT", "COUNT", "SUM", "AVG", "MIN", "MAX",
            "CASE", "WHEN", "THEN", "ELSE", "END", "IF", "COALESCE", "NULLS",
            "FIRST", "LAST", "ILIKE", "SIMILAR", "TO", "REGEXP", "CAST",
            "EXTRACT", "DATE", "TIME", "TIMESTAMP", "INTERVAL", "TRUE", "FALSE"
        }

    def _load_schema(self, schema_file_path):
        try:
            with open(schema_file_path, 'r', encoding='utf-8') as schema_file:
                schema = json.load(schema_file)
            return schema
        except FileNotFoundError:
            raise FileNotFoundError("Schema file not found")
        except json.JSONDecodeError:
            raise json.JSONDecodeError("Invalid JSON format", "", 0)
        except Exception as e:
            print("Error loading schema file:", e)
            return {}

    def _get_allowed_tables(self):
        """
        Get list of allowed table names from schema definition.
        """
        return list(self.schema_definition.keys()) if self.schema_definition else []

    def _get_allowed_columns(self, table_name):
        """
        Extract column names from the schema definition.
        Handles both simple list format and complex object format with metadata.
        """
        if not self.schema_definition:
            return []

        table_def = self.schema_definition.get(table_name, {})

        # Handle complex schema format with columns array
        if isinstance(table_def, dict) and 'columns' in table_def:
            columns = table_def['columns']
            if isinstance(columns, list):
                return [col['name'].lower() for col in columns if isinstance(col, dict) and 'name' in col]

        # Handle simple list format (backwards compatibility)
        elif isinstance(table_def, list):
            return [col.lower() for col in table_def]

        return []

    def _check_for_dangerous_keywords(self, query: str) -> Dict[str, Any]:
        """
        Checks for SQL keywords that could indicate dangerous operations.
        For read-only access, only SELECT statements are allowed.

        Args:
            query (str): The SQL query string.

        Returns:
            Dict[str, Any]: {"is_valid": True/False, "errors": ["messages"]}
        """
        query_upper = query.strip().upper()
        errors = []

        # READ-ONLY ENFORCEMENT: Only SELECT statements allowed
        if not query_upper.startswith('SELECT'):
            errors.append("Only SELECT statements are allowed for read-only access")

        # Check for any write operations (DML)
        write_operations = [
            r'\bINSERT\s+',
            r'\bUPDATE\s+',
            r'\bDELETE\s+',
            r'\bMERGE\s+'
        ]

        # DDL operations (structure changes)
        ddl_patterns = [
            r'\bCREATE\s+',
            r'\bALTER\s+',
            r'\bDROP\s+',
            r'\bTRUNCATE\s+',
            r'\bRENAME\s+'
        ]

        # Administrative and system operations
        admin_patterns = [
            r'\bGRANT\s+',
            r'\bREVOKE\s+',
            r'\bEXEC\s+',
            r'\bEXECUTE\s+',
            r'\bCALL\s+',
            r'\bxp_cmdshell\b',
            r'\bsp_executesql\b'
        ]

        # SQL injection patterns
        injection_patterns = [
            r'--',  # SQL comments
            r'/\*.*?\*/',  # Multi-line comments
            r';\s*(?:INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|EXEC|CALL)',  # Multiple statements with write ops
            r'UNION\s+(?:ALL\s+)?SELECT.*FROM\s+information_schema',  # Schema enumeration
            r'UNION\s+(?:ALL\s+)?SELECT.*FROM\s+sys\.',  # System table access
        ]

        # Dangerous WHERE clauses that might indicate injection
        dangerous_where_patterns = [
            r'\bWHERE\s+1\s*=\s*1\b',  # Always true condition
            r'\bWHERE\s+\'1\'\s*=\s*\'1\'\b',  # Always true condition
            r'\bOR\s+1\s*=\s*1\b',  # OR injection
            r'\bOR\s+\'1\'\s*=\s*\'1\'\b',  # OR injection
        ]

        all_patterns = write_operations + ddl_patterns + admin_patterns + injection_patterns + dangerous_where_patterns

        for pattern in all_patterns:
            matches = re.findall(pattern, query_upper, re.IGNORECASE | re.DOTALL)
            if matches:
                errors.append(f"Forbidden operation detected: {pattern}")

        return {"is_valid": len(errors) == 0, "errors": errors}

    def _extract_table_aliases(self, query: str) -> Dict[str, str]:
        """
        Extract table aliases from the query.

        Returns:
            Dict[str, str]: Mapping of alias to table name
        """
        aliases = {}

        # Pattern to match table aliases in FROM and JOIN clauses
        # Matches: table_name alias or table_name AS alias
        alias_pattern = r'(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+(?:AS\s+)?([a-zA-Z_][a-zA-Z0-9_]*)'

        matches = re.findall(alias_pattern, query, re.IGNORECASE)
        for table_name, alias in matches:
            aliases[alias.lower()] = table_name.lower()

        return aliases

    def _extract_tables_from_query(self, query: str) -> Set[str]:
        """
        Extract table names from FROM and JOIN clauses.

        Returns:
            Set[str]: Set of table names found in the query
        """
        tables = set()

        # Pattern to match table names in FROM and JOIN clauses
        # This handles both aliased and non-aliased tables
        table_patterns = [
            r'FROM\s+([a-zA-Z_][a-zA-Z0-9_]*)',
            r'JOIN\s+([a-zA-Z_][a-zA-Z0-9_]*)'
        ]

        for pattern in table_patterns:
            matches = re.findall(pattern, query, re.IGNORECASE)
            tables.update(match.lower() for match in matches)

        return tables

    def _extract_columns_from_query(self, query: str, table_aliases: Dict[str, str]) -> Dict[str, Set[str]]:
        """
        Extract column references from the query, organized by table.

        Args:
            query (str): The SQL query
            table_aliases (Dict[str, str]): Mapping of alias to table name

        Returns:
            Dict[str, Set[str]]: Mapping of table name to set of column names
        """
        columns_by_table = {}

        # Remove string literals and comments to avoid false matches
        cleaned_query = re.sub(r"'[^']*'", "", query)
        cleaned_query = re.sub(r'"[^"]*"', "", cleaned_query)
        cleaned_query = re.sub(r'--.*$', "", cleaned_query, flags=re.MULTILINE)

        # Pattern to match qualified column references (table.column or alias.column)
        qualified_column_pattern = r'\b([a-zA-Z_][a-zA-Z0-9_]*)\.([a-zA-Z_][a-zA-Z0-9_]*)\b'

        matches = re.findall(qualified_column_pattern, cleaned_query, re.IGNORECASE)

        for table_or_alias, column in matches:
            table_or_alias = table_or_alias.lower()
            column = column.lower()

            # Resolve alias to actual table name
            table_name = table_aliases.get(table_or_alias, table_or_alias)

            if table_name not in columns_by_table:
                columns_by_table[table_name] = set()
            columns_by_table[table_name].add(column)

        return columns_by_table

    def _validate_schema_elements(self, query: str) -> Dict[str, Any]:
        """
        Validates table and column names in the query against the provided schema.

        Args:
            query (str): The SQL query string.

        Returns:
            Dict[str, Any]: {"is_valid": True/False, "errors": ["messages"]}
        """
        errors = []
        is_valid = True

        allowed_tables = self._get_allowed_tables()
        if not allowed_tables:
            return {"is_valid": True, "errors": []}

        # Extract tables and aliases
        found_tables = self._extract_tables_from_query(query)
        table_aliases = self._extract_table_aliases(query)

        # Validate table names
        for table in found_tables:
            if table not in [t.lower() for t in allowed_tables]:
                errors.append(f"Invalid table '{table}' found in query.")
                is_valid = False

        # Validate column names
        columns_by_table = self._extract_columns_from_query(query, table_aliases)

        for table_name, columns in columns_by_table.items():
            # Find the actual table name (case-insensitive)
            actual_table_name = None
            for allowed_table in allowed_tables:
                if allowed_table.lower() == table_name.lower():
                    actual_table_name = allowed_table
                    break

            if actual_table_name:
                allowed_columns = self._get_allowed_columns(actual_table_name)

                if allowed_columns:  # Only validate if columns are defined for the table
                    for column in columns:
                        if column.lower() not in [col.lower() for col in allowed_columns]:
                            # Check if it's a function or keyword before reporting as invalid
                            if column.upper() not in self.keywords:
                                # Provide helpful error message with available columns
                                available_cols = ', '.join(allowed_columns)
                                errors.append(
                                    f"Invalid column '{column}' for table '{actual_table_name}'. Available columns: [{available_cols}]")
                                is_valid = False

        return {"is_valid": is_valid, "errors": errors}

    def validate(self, query: str) -> Dict[str, Any]:
        """
        Validate the SQL query for read-only safety and schema compliance.

        Args:
            query (str): The SQL query to validate

        Returns:
            Dict[str, Any]: {"is_valid": True/False, "errors": ["messages"]}
        """
        all_errors = []
        is_valid = True
        # Ensure query is not empty
        if not query or not query.strip():
            return {"is_valid": False, "errors": ["Empty query provided"]}

        # Check for dangerous keywords and enforce read-only access
        dangerous_result = self._check_for_dangerous_keywords(query)
        if not dangerous_result["is_valid"]:
            all_errors.extend(dangerous_result["errors"])
            is_valid = False

        # Only validate schema if the query passed the read-only check
        # and we have schema definition
        if is_valid and self.schema_definition:
            schema_result = self._validate_schema_elements(query)
            if not schema_result["is_valid"]:
                all_errors.extend(schema_result["errors"])
                is_valid = False
        return {"is_valid": is_valid, "errors": all_errors}