import re
import json
from typing import List, Dict, Any, Optional
import os


class SQLValidator:
    """
       A class to validate SQL queries generated by the AI chatbot.
       It checks for safety (e.g., preventing dangerous operations)
       and adherence to a defined database schema.
    """
    def __init__(self, schema_file_path):
        self.schema_definition = self._load_schema(schema_file_path)
        self.keywords = {"SELECT", "FROM", "WHERE", "JOIN", "INSERT", "UPDATE", "DELETE",
            "AND", "OR", "NOT", "GROUP BY", "ORDER BY", "LIMIT", "OFFSET",
            "HAVING", "AS", "ON", "IN", "LIKE", "BETWEEN", "IS NULL",
            "CREATE", "ALTER", "DROP", "TRUNCATE", "UNION", "ALL", "EXISTS"}

    def _load_schema(self, schema_file_path):
        try:
            with open(schema_file_path, 'r', encoding='utf-8') as schema_file:
                schema = json.load(schema_file)
            return schema
        except FileNotFoundError:
            raise FileNotFoundError("Schema file not found")
        except json.decoder.JSONDecodeError:
            raise json.decoder.JSONDecodeError("Invalid JSON format")
        except Exception as e:
            print("Error loading schema file:", e)
            return{}

    def _get_allowed_tables(self):
        return self.schema_definition.keys() if self.schema_definition else []

    def _get_allowed_columns(self, table_name):
        return self.schema_definition.get(table_name, []) if self.schema_definition else []

    def _check_for_dangerous_keywords(self, query: str) -> bool:
        """
        Checks for SQL keywords that could indicate dangerous operations (e.g., DDL,
        multiple statements, unauthorized modifications).

        Args:
            query (str): The SQL query string.

        Returns:
            bool: True if no dangerous keywords are found, False otherwise.
        """
        query_upper = query.upper()
        # Examples of dangerous keywords/patterns (can be expanded)
        dangerous_patterns = [
            r'CREATE\s+', r'ALTER\s+', r'DROP\s+', r'TRUNCATE\s+',
            r'--|;|\/\*',  # Comment or multiple statement injection
            r'UNION\s+ALL\s+SELECT',  # Basic check for union-based attacks
            r'EXEC\s+', r'xp_cmdshell',  # SQL Server specific
            r'DELETE\s+FROM\s+\w+\s*WHERE\s+1\s*=\s*1',  # Catching overly broad DELETEs
            r'UPDATE\s+\w+\s*SET\s+\w+\s*=\s*\w+\s*WHERE\s+1\s*=\s*1',  # Catching overly broad UPDATEs
        ]
        for pattern in dangerous_patterns:
            if re.search(pattern, query_upper):
                return False
        return True

    def _validate_schema_elements(self, query: str) -> Dict[str, Any]:
        """
        Validates table and column names in the query against the provided schema.
        This is a simplified example and might require a more robust SQL parser
        for complex queries.

        Args:
            query (str): The SQL query string.

        Returns:
            Dict[str, Any]: {"is_valid": True/False, "errors": ["messages"]}
        """
        errors = []
        is_valid = True
        query_upper = query.upper()

        allowed_tables = self._get_allowed_tables()
        if not allowed_tables:
            return {"is_valid": True, "errors": []}

        # Basic regex to find table names (might need refinement for complex queries)
        found_tables = set(re.findall(r'(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)', query_upper))

        for table in found_tables:
            if table not in allowed_tables:
                errors.append(f"Invalid table '{table}' found in query.")
                is_valid = False
            else:
                # Basic column validation (more complex, might need a proper parser)
                allowed_columns = self._get_allowed_columns(table)
                if allowed_columns:  # Only validate if columns are defined for the table
                    potential_columns = set(
                        re.findall(r'(?:SELECT|WHERE|ORDER BY|GROUP BY)\s+.*?\b([a-zA-Z_][a-zA-Z0-9_]*)\b',
                                   query_upper))
                    # Filter out SQL keywords
                    potential_columns = {col for col in potential_columns if col not in self.keywords}

                    for col in potential_columns:
                        if col not in allowed_columns:
                            errors.append(f"Potentially invalid column '{col}' for table '{table}' found in query.")
                            is_valid = False
        return {"is_valid": is_valid, "errors": errors}

    def validate(self, query):
        errors = []
        is_valid = True
        query = query.upper()

        result_dangerous = self._check_for_dangerous_keywords(query)
        if not result_dangerous:
            errors.append("Dangerous keywords found in query.")
            is_valid = False

        if self.schema_definition:
            result_valid_schema_elements = self._validate_schema_elements(query)
            if not result_valid_schema_elements["is_valid"]:
                errors.append(result_valid_schema_elements["errors"])
                is_valid = False

        return {"is_valid": is_valid, "errors": errors}
